### PR TITLE
only calculate clock once

### PR DESCRIPTION
**Pull request by twillouer**
Hi,

a little trick, but System.currentTimeMillis is very expensive in Java.

On my computer, with a very bad test, I gain 2 seconds (8 vs 6s) with this PR.

Thanks for you work btw !

### CODE REVIEW

**Comment by twillouer** [comment]
any news ?

**Comment by hengyunabc** [comment]
Thank you very much.

**Comment by hengyunabc** [comment]
Version 0.0.4 has push to central repository.

```xml
<dependency>
    <groupId>io.github.hengyunabc</groupId>
    <artifactId>metrics-zabbix</artifactId>
    <version>0.0.4</version>
</dependency>
```

**Comment by twillouer** [comment]
thanks !

**Pull request merged**
